apiVersion: v1
kind: PersistentVolume
metadata:
    name: consul-server-0
    labels:
        type: local
spec:
    storageClassName: consul-data
    capacity:
        storage: 256Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/data/consul-0'
