apiVersion: v1
kind: ServiceAccount
metadata:
    name: k8s-consul
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: consul-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
            annotations:
                "consul.hashicorp.com/connect-inject": "true"
        spec:
            containers:
            - name: k8s-consul
              image: gitlab.ksungcaya.com:5000/ksungcaya/k8s-consul
              env:
                - name: JWT_PATH
                  value: /var/run/secrets/kubernetes.io/serviceaccount/token
                - name: VAULT_ADDR
                  value: "http://vault:8200"
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 8080
                name: http
            imagePullSecrets:
            - name: gitlab-regcred
            serviceAccountName: k8s-consul
