apiVersion: v1
kind: PersistentVolume
metadata:
    name: data-vault-0
    labels:
        type: local
spec:
    storageClassName: standard
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/data'
